### ISSUE TITLE
A question about this line, why use object extends T ?

### ISSUE THREAD

**Issue by zhangwilling** [ahejlsberg/tsconf2020-demos#1]
First, thanks for your share about ts new feature at tsconf2020. 

Template feature is amazing, the example `getProp` looks really really awesome, but i am curious about this line

https://github.com/ahejlsberg/tsconf2020-demos/blob/b83b9698a8ffd40c63afa63905142ec5c30eb604/template/main.ts#L111

We usally use `T extends object` to make sure T is `object` type (non-primative type). It's my first time to see the usage above, i don't know what's it mean for. 

I search all the internet but not get an answer. 

Could please give me some guide about this usage ? 

Thanks anyway!

**Comment by ahejlsberg** [comment]
It's simply a check to see if `T` is a _supertype_ of `object` (which is the same as `object` being a _subtype_ of `T`). In other words, it's a check to see of `T` is a type that is less specific than `object`, such as `any`, `unknown`, `{}`. For those types, we have no specific knowledge about their properties, so the result is just `string`.
